[package]
name = "status-bar"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8"
gtk4-layer-shell = "0.3"
notify = "6.1.1"
tokio = { version = "1", features = ["full"] }
hyprland = "0.3.13"
