[workspace]
resolver = "2"
members = [
  "crates/status-bar",

  "crates/bar",

  "crates/services",
  "crates/utils",
  "crates/datemenu", "crates/quicksettings"
]

default-members = ["crates/status-bar"]

[workspace.lints.clippy]
dbg_macro = "allow"
todo = "allow"
