# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [{
  name = "1220ee3e898557547c4096198a4451c264f1af01f34143344e0e8794c4d8da815b2e";
  path = fetchzip {
    url =
      "https://github.com/DerryAlex/zig-gir-ffi/releases/download/0.10.2/gtk4.tar.gz";
    hash = "sha256-l5ER9qOMIwcSeWCncB3XgBM0SQjq12vrLrE72QRM4YM=";
  };
}]
