# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "gi-0.12.0-YzYLXzukPQBHOYG80AFLda1fK83Z95GzomKFCP9Z2j-m";
    path = fetchzip {
      url = "https://github.com/DerryAlex/zig-gir-ffi/releases/download/0.12.0%2Brc1/gi.tar.gz";
      hash = "sha256-4ibrKi0TNFXABk7r30FHClrcP9L6YcvHHEy7kEz3dGY=";
    };
  }
]
