// This file is auto-generated by zig-gir-ffi
const freetype2 = @This();
pub const core = @import("core");
const std = @import("std");
const config = core.config;
pub const Bitmap = opaque {};
pub const Face = opaque {};
pub const Library = opaque {};
test {
    @setEvalBranchQuota(1_000_000);
    std.testing.refAllDecls(@This());
}
